# Generated by Django 4.2.16 on 2025-04-03 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fitness", "0002_userprofile_height_userprofile_sex_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakfast", models.TextField(blank=True, null=True)),
                ("breakfast_calories", models.IntegerField(blank=True, null=True)),
                ("lunch", models.TextField(blank=True, null=True)),
                ("lunch_calories", models.IntegerField(blank=True, null=True)),
                ("dinner", models.TextField(blank=True, null=True)),
                ("dinner_calories", models.IntegerField(blank=True, null=True)),
                ("snacks", models.TextField(blank=True, null=True)),
                ("snacks_calories", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
