# Generated by Django 4.2.16 on 2025-04-03 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0003_dietplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietplan",
            name="breakfast",
        ),
        migrations.RemoveField(
            model_name="dietplan",
            name="breakfast_calories",
        ),
        migrations.RemoveField(
            model_name="dietplan",
            name="dinner",
        ),
        migrations.RemoveField(
            model_name="dietplan",
            name="dinner_calories",
        ),
        migrations.RemoveField(
            model_name="dietplan",
            name="lunch",
        ),
        migrations.RemoveField(
            model_name="dietplan",
            name="lunch_calories",
        ),
        migrations.RemoveField(
            model_name="dietplan",
            name="snacks",
        ),
        migrations.RemoveField(
            model_name="dietplan",
            name="snacks_calories",
        ),
        migrations.AddField(
            model_name="dietplan",
            name="has_diet_plan",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DailyDietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("breakfast", models.TextField(blank=True, null=True)),
                ("breakfast_calories", models.IntegerField(blank=True, null=True)),
                ("lunch", models.TextField(blank=True, null=True)),
                ("lunch_calories", models.IntegerField(blank=True, null=True)),
                ("dinner", models.TextField(blank=True, null=True)),
                ("dinner_calories", models.IntegerField(blank=True, null=True)),
                ("snacks", models.TextField(blank=True, null=True)),
                ("snacks_calories", models.IntegerField(blank=True, null=True)),
                (
                    "diet_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_plans",
                        to="fitness.dietplan",
                    ),
                ),
            ],
            options={
                "unique_together": {("diet_plan", "day_of_week")},
            },
        ),
    ]
