# Generated by Django 4.2.16 on 2025-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0004_remove_dietplan_breakfast_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notification_preference",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly"), ("none", "None")],
                default="none",
                max_length=10,
            ),
        ),
    ]
