# Generated by Django 4.2.16 on 2025-04-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0005_userprofile_notification_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
