# Generated by Django 4.2.16 on 2025-04-04 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fitness", "0008_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("steps", models.IntegerField(blank=True, null=True)),
                ("calories_burnt", models.IntegerField(blank=True, null=True)),
                ("sleep_hours", models.FloatField(blank=True, null=True)),
                (
                    "blood_pressure",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
