# Generated by Django 4.2.16 on 2025-04-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0010_communitymessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthdata",
            name="oxygen_level",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
