# Generated by Django 4.2.16 on 2025-04-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0011_healthdata_oxygen_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailydietplan",
            name="breakfast_carbs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="breakfast_fat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="breakfast_protein",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="dinner_carbs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="dinner_fat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="dinner_protein",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="lunch_carbs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="lunch_fat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="lunch_protein",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="snacks_carbs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="snacks_fat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailydietplan",
            name="snacks_protein",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
