# Generated by Django 5.2 on 2025-04-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_userprofile_country_userprofile_diet_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diet_preference',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non-vegetarian', 'Non-Vegetarian')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ethnic_group',
            field=models.CharField(blank=True, choices=[('asian', 'Asian'), ('black', 'Black/African'), ('hispanic', 'Hispanic/Latino'), ('middle_eastern', 'Middle Eastern'), ('white', 'White/Caucasian'), ('pacific_islander', 'Pacific Islander'), ('native_american', 'Native American'), ('mixed', 'Mixed Ethnicity'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
