# Generated by Django 5.2 on 2025-04-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_alter_userprofile_diet_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light Activity'), ('moderate', 'Moderate Activity'), ('active', 'Very Active'), ('extra_active', 'Extra Active')], max_length=20, null=True),
        ),
    ]
