# Generated by Django 5.2 on 2025-04-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_userprofile_activity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_level',
        ),
    ]
